### PR TITLE
Add toJSON to VariableType

### PR DESCRIPTION
**Pull request by terion-name**
VariableType to render with dollar prefix in json.stringify

### CODE REVIEW

**Comment by dupski** [comment]
Hi @terion-name - does this affect any of the tests?  If it is new functionality could you add a test for it please? Cheers

**Comment by terion-name** [comment]
@dupski it doesn't affect anything, stringifying is a special case but ok, I'll add tests for this

**Comment by terion-name** [comment]
@dupski added

**Comment by terion-name** [comment]
the whole idea is that when you call JSON.stringify on source json, you get variables marked with dollar prefix. I've faced some cases when this is useful. Maybe there will be some sense in adding revert parsing in future

**Pull request merged**
