### PR TITLE
add includeFalsyKeys option

### PR DESCRIPTION
**Pull request by bret-hubbard**
Reference issue #14

### CODE REVIEW

**Comment by dupski** [comment]
Cheers for this. I will take a look and merge at the weekend :)

**Comment by dupski** [comment]
Cool. Could you add a test for what should happen if an array contains a mix of numbers and objects, with a number or null as the first item. I guess we could have it so it just returns the first object found? Also what happens when an array has strings?

**Comment by bret-hubbard** [comment]
Oh sorry @dupski! I didn't realize github would include the second commit in the PR. I was about to add a comment to the other issue I raised about how you brought up really good issues I hadn't thought of but I thought this implementation might work well if you're interested.

I like the idea of finding the first that is an object and if it doesn't exist then it will just add the key. I will update the PR with those changes and a test with an array mixed with an object, number, or null.

If you don't like the idea of this addition after seeing the implementation let me know and I will revert those commits for just the original change.

Thanks!

**Comment by dupski** [comment]
Thanks @bret-hubbard , all good. Just shipped as `v1.9.0` :)

**Comment by dupski** [comment]
Also, good tests. Thanks :)

**Comment by bret-hubbard** [comment]
Thank you @dupski! Let me know if you need any help with maintenance in the future, happy to help! Thanks for your work on this library!

**Pull request merged**
