### PR TITLE
adds support for inline fragments

### PR DESCRIPTION
**Pull request by jeniffer9**
- adds support for inline fragments
- adds unit tests
- updates version to 1.8.0
- updates README

### CODE REVIEW

**Comment by dupski** [comment]
Nice, thanks @jeniffer9 It might take me a couple of days to get this merged and released as I'm out for the next couple of evenings but will get it out asap :)

**Comment by jeniffer9** [comment]
@dupski No problem, take your time! :)

**Comment by dupski** [comment]
Yo! Quick update on this, I've scheduled some time on Thursday (NZ time) to get this merged :)

**Comment by jeniffer9** [comment]
Alright cool, thanks for the update! :)

**Comment by dupski** [comment]
Many thanks for this @jeniffer9 - released as `v1.8.0`!

Couple of minor tweaks:
* I had to fix a couple of linting errors. (you can run `npm run build` on the project to see these in future)
* I've renamed `__fragmentName` to `__typeName` since it references the name of a GraphQL object type rather than a fragment name.
* You don't need to increment the version number in `package.json` as this happens as part of the tag and release process

Thanks for your contribution :)

**Comment by jeniffer9** [comment]
cool, thank you!
I'll take those points into account for next time! :)

**Pull request merged**
